ARG FUNCTION_DIR="/home/aayu2/project2.1/"
ARG RUNTIME_VERSION="3.8"

FROM python:${RUNTIME_VERSION}-alpine AS build-image

# Install required dependencies and libraries
RUN apk --no-cache add ffmpeg && \
    python${RUNTIME_VERSION} -m pip install --upgrade pip

# Create function directory
RUN mkdir -p ${FUNCTION_DIR}

# Install Lambda Runtime Interface Client for Python
RUN python${RUNTIME_VERSION} -m pip install awslambdaric --target ${FUNCTION_DIR}

# Final image
FROM python:${RUNTIME_VERSION}-alpine
ARG FUNCTION_DIR
WORKDIR ${FUNCTION_DIR}

# Copy dependencies
COPY --from=build-image ${FUNCTION_DIR} ${FUNCTION_DIR}

# Copy requirements and install them
COPY requirements.txt ${FUNCTION_DIR}
RUN python${RUNTIME_VERSION} -m pip install -r requirements.txt --target ${FUNCTION_DIR}

# Copy function code
COPY handler.py ${FUNCTION_DIR}

# Set up entry point
COPY entry.sh /entry.sh
RUN chmod 777 /entry.sh

# Set the CMD to your handler
ENTRYPOINT [ "/entry.sh" ]
CMD [ "handler.handler" ]
